######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 7 21:34:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h window.h Wuziqi.h
SOURCES += dialog.cpp main.cpp window.cpp Wuziqi.cpp
